import "dart:math";

class MotivationQuotes {
  final List quotes = [
    "YOU MADE IT THIS FAR, YOU GOTTA KEEP THE MOMENTUM UP",
    "DO WHAT YOU CAN WITH WHAT YOU HAVE. THAT'S ALL THERE IS TO IT",
    "IN ORDER TO SUCCEED, WE MUST FIRST BELIEVE THAT WE CAN",
    "LIFE BE LIKE THAT SOMETIME. TAKE THE L AND USE IT AS A CRUTCH TO THE NEXT BATTLE",
    "YOU LIVED THROUGH 2020, THAT SHOULD COUNT FOR SOMETHING",
    "DO OR DO NOT. THERE IS NO TRY",
    "DO NOT FEEL SORRY FOR YOURSELF. BE BETTER FOR YOURSELF",
    "YOU CAN'T REALLY BEAT THE PERSON WHO NEVER GIVES UP. BE THAT PERSON WHO NEVER GIVES UP",
    "GOING THROUGH HELL? KEEP GOING. IT'S THE ONLY WAY OUT",
    "IT SUCKS NOW, BUT HOW COOL WILL IT BE WHEN YOU MAKE IT?",
    "I KNOW ALL MY NIGGAS GONNA MAKE IT. SO YOU GOT THIS IN THE BAG ALREADY",
    "SHIT WORKS OUT IN THE END. SO YOU KNOW, IF IT AIN'T WORK OUT NOW, IT AIN'T THE END",
    "DID YOU REMEMBER TO EAT & TAKE A BREAK? EVEN VIDEO GAME CHARACTERS HAVE SAVE POINTS.",
    "WHEN YOU FEEL DOWN, STOP FEELING DOWN AND BE AWESOME INSTEAD",
    "YOU AIN'T GONE THROUGH HELL ALL THOSE YEARS FOR SHIT TO HIT THE FAN. KEEP WORKING AT IT."
  ];

  final List colors = [
    0xFFffdd33,
    0xFF4da6ff,
    0xFF00cc44,
    0xFFe600e6,
  ];

  List getQuote() {
    String quote = quotes[Random().nextInt(quotes.length)];
    int color = colors[Random().nextInt(colors.length)];

    return [quote, color];
  }
}
